version: '3'

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - project

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - project
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www//wordpress
    networks:
      - project
    depends_on:
      - mariadb
    
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  project:
    driver: bridge
