version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - project
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:  # Change here
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # If you need a root password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - project

  wordpress:
    image: wordpress
    container_name: wordpress
    environment:  # Change here
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_TITLE: arafa.42.fr # Add other relevant WordPress config here
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - project
    depends_on:
      - mariadb

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  project:
    driver: bridge
