version: '3'

services:
  mariadb:
    container_name: mariadb                # Le nom du container
    networks:
      - inception                          # Réseau auquel il appartient
    build: 
      context: requirements/mariadb         # Emplacement du Dockerfile
      dockerfile: Dockerfile                # Nom du Dockerfile
    env_file: .env                         # Fichier d'environnement pour les variables
    volumes:                               # Montages de volumes
      - mariadb:/var/lib/mysql
    restart: unless-stopped                # Redémarre tant qu'il n'est pas stoppé
    expose:                                # Port à exposer
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:                            # NGINX ne démarre pas tant que WordPress n'a pas démarré
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"                          # Port exposé à la machine locale
    restart: on-failure                    # Le container redémarre uniquement en cas de crash

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:                            # WordPress démarre uniquement après MariaDB
      - mariadb
    restart: on-failure
    expose: 
      - "9000"
volumes:
  wordpress:
    driver: local # ici nous stockons le volume en local
    driver_opts:
    type: 'none' 									# aucun type spécifique
    o: 'bind
    device: '/Users/login/data/wordpress' 		#Ou stocker le dossier sur votre ordinateur en local
  mariadb:
    driver: local
    driver_opts:
    type: 'none' 
    o: 'bind'										 # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
    device: '/Users/login/data/mariadb'			#Ou stocker le dossier sur votre ordinateur en local


networks:
  inception:
